###  Exercise 1
Your goals are:

1. Calculate the total sales for Product B (the second row).
2. Identify which months had sales greater than 130 for Product C (the third row) using boolean masking.
3. Extract the sales data for all products for the months of Feb and Mar (the middle two columns).

In [6]:
import torch

# Sales data for 3 products over 4 months
sales_data = torch.tensor([[100, 120, 130, 110],   # Product A
                           [ 90,  95, 105, 125],   # Product B
                           [140, 115, 120, 150]    # Product C
                          ], dtype=torch.float32)

print("ORIGINAL SALES DATA:\n\n", sales_data)
print("-" * 45)

ORIGINAL SALES DATA:

 tensor([[100., 120., 130., 110.],
        [ 90.,  95., 105., 125.],
        [140., 115., 120., 150.]])
---------------------------------------------


In [24]:
# 1.
sales_data[1].sum()

tensor(415.)

In [25]:
# 2
product_c = sales_data[2:]
product_c > 130

tensor([[ True, False, False,  True]])

In [26]:
# 3
sales_data[:, 1:3]

tensor([[120., 130.],
        [ 95., 105.],
        [115., 120.]])

### Exercise 2: Image Batch Transformation

You're working on a computer vision model and have a batch of 4 grayscale images, each with a size of 3 pixels high by 2 pixels wide. The data is currently in a tensor with the shape `[4, 3, 2]`, which represents `[batch_size, height, width]`.

For processing with certain deep learning frameworks, you need to transform this data into the `[batch_size, channels, height, width]` format. Since the images are grayscale, **you'll need to**:

1. Add a new dimension of size 1 at index 1 to represent the color channel.
2. After adding the channel, you realize the model expects the shape `[batch_size, height, width, channels]`. Transpose the tensor to move the channel dimension to the last position without scrambling the height and width. Use `.transpose()` multiple times.


In [27]:
# A batch of 4 grayscale images, each 3x2
image_batch = torch.rand(4, 3, 2)

print("ORIGINAL BATCH SHAPE:", image_batch.shape)
print("-" * 45)

ORIGINAL BATCH SHAPE: torch.Size([4, 3, 2])
---------------------------------------------


In [45]:
image_batch

tensor([[[0.5625, 0.7971],
         [0.7702, 0.3670],
         [0.6649, 0.3138]],

        [[0.3938, 0.4729],
         [0.7348, 0.9447],
         [0.7460, 0.2691]],

        [[0.4349, 0.9196],
         [0.4167, 0.0301],
         [0.5958, 0.6618]],

        [[0.0639, 0.2344],
         [0.0028, 0.3956],
         [0.7131, 0.5745]]])

In [42]:
image_batch_with_channel = image_batch.unsqueeze(1)
image_batch_with_channel

tensor([[[[0.5625, 0.7971],
          [0.7702, 0.3670],
          [0.6649, 0.3138]]],


        [[[0.3938, 0.4729],
          [0.7348, 0.9447],
          [0.7460, 0.2691]]],


        [[[0.4349, 0.9196],
          [0.4167, 0.0301],
          [0.5958, 0.6618]]],


        [[[0.0639, 0.2344],
          [0.0028, 0.3956],
          [0.7131, 0.5745]]]])

In [ ]:
temp_tensor = image_batch_with_channel.transpose(1,2)
image_batch_transposed = temp_tensor.transpose(2, 3)
image_batch_transposed

tensor([[[[0.5625, 0.7971]],

         [[0.7702, 0.3670]],

         [[0.6649, 0.3138]]],


        [[[0.3938, 0.4729]],

         [[0.7348, 0.9447]],

         [[0.7460, 0.2691]]],


        [[[0.4349, 0.9196]],

         [[0.4167, 0.0301]],

         [[0.5958, 0.6618]]],


        [[[0.0639, 0.2344]],

         [[0.0028, 0.3956]],

         [[0.7131, 0.5745]]]])

In [ ]:
temp_tensor = image_batch_with_channel.transpose(1,3)
image_batch_transposed = temp_tensor.transpose(2, 3)
image_batch_transposed

tensor([[[[0.5625, 0.7702, 0.6649]],

         [[0.7971, 0.3670, 0.3138]]],


        [[[0.3938, 0.7348, 0.7460]],

         [[0.4729, 0.9447, 0.2691]]],


        [[[0.4349, 0.4167, 0.5958]],

         [[0.9196, 0.0301, 0.6618]]],


        [[[0.0639, 0.0028, 0.7131]],

         [[0.2344, 0.3956, 0.5745]]]])

In [ ]:
image_batch_transposed = image_batch_with_channel.permute(0, 2, 3, 1)
image_batch_transposed

tensor([[[[0.5625],
          [0.7971]],

         [[0.7702],
          [0.3670]],

         [[0.6649],
          [0.3138]]],


        [[[0.3938],
          [0.4729]],

         [[0.7348],
          [0.9447]],

         [[0.7460],
          [0.2691]]],


        [[[0.4349],
          [0.9196]],

         [[0.4167],
          [0.0301]],

         [[0.5958],
          [0.6618]]],


        [[[0.0639],
          [0.2344]],

         [[0.0028],
          [0.3956]],

         [[0.7131],
          [0.5745]]]])

In [66]:
arr = torch.tensor([[2,3,4],[6,2,1]], dtype=torch.float32)
arr, arr.shape

(tensor([[2., 3., 4.],
         [6., 2., 1.]]),
 torch.Size([2, 3]))

In [67]:
new_arr = arr.unsqueeze(0)
new_arr, new_arr.shape

(tensor([[[2., 3., 4.],
          [6., 2., 1.]]]),
 torch.Size([1, 2, 3]))

In [68]:
new_arr = arr.unsqueeze(1)
new_arr, new_arr.shape

(tensor([[[2., 3., 4.]],
 
         [[6., 2., 1.]]]),
 torch.Size([2, 1, 3]))

In [69]:
new_arr = arr.unsqueeze(2)
new_arr, new_arr.shape

(tensor([[[2.],
          [3.],
          [4.]],
 
         [[6.],
          [2.],
          [1.]]]),
 torch.Size([2, 3, 1]))

### Exercise 3: Combining and Weighting Sensor Data

You're building an environment monitoring system that uses two sensors: one for temperature and one for humidity. You receive data from these sensors as two separate 1D tensors.

**Your task is to**:

1. **Concatenate** the two tensors into a single `2x5` tensor, where the first row is temperature data and the second is humidity data.
2. Create a `weights` tensor `torch.tensor([0.6, 0.4])`.
3. Use **broadcasting and element-wise multiplication** to apply these weights to the combined sensor data. The temperature data should be multiplied by 0.6 and the humidity data by 0.4.
4. Finally, calculate the **weighted average** for each time step by **summing** the weighted values along `dim=0` and **dividing** by the sum of the weights.

In [98]:
# Sensor readings (5 time steps)
temperature = torch.tensor([22.5, 23.1, 21.9, 22.8, 23.5])
humidity = torch.tensor([55.2, 56.4, 54.8, 57.1, 56.8])

print("TEMPERATURE DATA: ", temperature)
print("HUMIDITY DATA:    ", humidity)
print("-" * 45)

### START CODE HERE ###

# 1. Concatenate the two tensors.
# Note: You need to unsqueeze them first to stack them vertically.
combined_data = torch.cat((temperature.unsqueeze(1), humidity.unsqueeze(1)), dim=1)

# 2. Create the weights tensor.
weights = torch.tensor([0.6, 0.4]).unsqueeze(0)

# 3. Apply weights using broadcasting.
# You need to reshape weights to [2, 1] to broadcast across columns.
weighted_data = combined_data*weights

# 4. Calculate the weighted average for each time step.
#    (A true average = weighted sum / sum of weights)
weighted_sum = torch.sum(weighted_data, dim=1)
weighted_average = weighted_sum / torch.sum(weights)

### END CODE HERE ###

print("\nCOMBINED DATA (2x5):\n\n", combined_data, combined_data.shape)
print(weights, weights.shape)
print("\nWEIGHTED DATA:\n\n", weighted_data)
print("\nWEIGHTED SUM:", weighted_sum)
print("\nWEIGHTED AVERAGE:", weighted_average)

TEMPERATURE DATA:  tensor([22.5000, 23.1000, 21.9000, 22.8000, 23.5000])
HUMIDITY DATA:     tensor([55.2000, 56.4000, 54.8000, 57.1000, 56.8000])
---------------------------------------------

COMBINED DATA (2x5):

 tensor([[22.5000, 55.2000],
        [23.1000, 56.4000],
        [21.9000, 54.8000],
        [22.8000, 57.1000],
        [23.5000, 56.8000]]) torch.Size([5, 2])
tensor([[0.6000, 0.4000]]) torch.Size([1, 2])

WEIGHTED DATA:

 tensor([[13.5000, 22.0800],
        [13.8600, 22.5600],
        [13.1400, 21.9200],
        [13.6800, 22.8400],
        [14.1000, 22.7200]])

WEIGHTED SUM: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])

WEIGHTED AVERAGE: tensor([35.5800, 36.4200, 35.0600, 36.5200, 36.8200])


### Exercise 4: Feature Engineering for Taxi Fares

You are working with a dataset of taxi trips. You have a tensor, `trip_data`, where each row is a trip and the columns represent **[distance (km), hour_of_day (24h)]**.

**Your goal** is to engineer a new binary feature called `is_rush_hour_long_trip`. This feature should be `True` (or `1`) only if a trip meets **both** of the following criteria:

* It's a **long trip** (distance > 10 km).
* It occurs during a **rush hour** (8-10 AM or 5-7 PM, i.e., `[8, 10)` or `[17, 19)`).

To achieve this, you will need to:

1. **Slice** the `trip_data` tensor to isolate the `distance` and `hour` columns.
2. Use **logical and comparison operators** to create boolean masks for each condition (long trip, morning rush, evening rush).
3. Combine these masks to create the final `is_rush_hour_long_trip` feature.
4. **Reshape** this new 1D feature tensor into a 2D column vector and convert its data type to float so it can be combined with the original data.

In [116]:
# Data for 8 taxi trips: [distance, hour_of_day]
trip_data = torch.tensor([
    [5.3, 7],   # Not rush hour, not long
    [12.1, 9],  # Morning rush, long trip -> RUSH HOUR LONG
    [15.5, 13], # Not rush hour, long trip
    [6.7, 18],  # Evening rush, not long
    [2.4, 20],  # Not rush hour, not long
    [11.8, 17], # Evening rush, long trip -> RUSH HOUR LONG
    [9.0, 9],   # Morning rush, not long
    [14.2, 8]   # Morning rush, long trip -> RUSH HOUR LONG
], dtype=torch.float32)


print("ORIGINAL TRIP DATA (Distance, Hour):\n\n", trip_data)
print("-" * 55)


### START CODE HERE ###

# 1. Slice the main tensor to get 1D tensors for each feature.
distances = trip_data[:, 0]
hours = trip_data[:, 1]

# 2. Create boolean masks for each condition.
is_long_trip = distances > 10
is_morning_rush = (8 <= hours) & (hours < 10)
is_evening_rush = (17 <= hours) & (hours < 19)

# 3. Combine masks to identify rush hour long trips.
# A trip is a rush hour long trip if it's (a morning OR evening rush) AND a long trip.
is_rush_hour_long_trip_mask = is_long_trip & ( is_morning_rush | is_evening_rush )
# print(is_rush_hour_long_trip_mask.unsqueeze(1))

# 4. Reshape the new feature into a column vector and cast to float.
new_feature_col = is_rush_hour_long_trip_mask.unsqueeze(1)

### END CODE HERE ###

print("\n'IS RUSH HOUR LONG TRIP' MASK: ", is_rush_hour_long_trip_mask)
print("\nNEW FEATURE COLUMN (Reshaped):\n\n", new_feature_col)

# You can now concatenate this new feature to the original data
enhanced_trip_data = torch.cat((trip_data, new_feature_col), dim=1)
print("\nENHANCED DATA (with new feature at the end):\n\n", enhanced_trip_data)

ORIGINAL TRIP DATA (Distance, Hour):

 tensor([[ 5.3000,  7.0000],
        [12.1000,  9.0000],
        [15.5000, 13.0000],
        [ 6.7000, 18.0000],
        [ 2.4000, 20.0000],
        [11.8000, 17.0000],
        [ 9.0000,  9.0000],
        [14.2000,  8.0000]])
-------------------------------------------------------

'IS RUSH HOUR LONG TRIP' MASK:  tensor([False,  True, False, False, False,  True, False,  True])

NEW FEATURE COLUMN (Reshaped):

 tensor([[False],
        [ True],
        [False],
        [False],
        [False],
        [ True],
        [False],
        [ True]])

ENHANCED DATA (with new feature at the end):

 tensor([[ 5.3000,  7.0000,  0.0000],
        [12.1000,  9.0000,  1.0000],
        [15.5000, 13.0000,  0.0000],
        [ 6.7000, 18.0000,  0.0000],
        [ 2.4000, 20.0000,  0.0000],
        [11.8000, 17.0000,  1.0000],
        [ 9.0000,  9.0000,  0.0000],
        [14.2000,  8.0000,  1.0000]])
